// AUTO-GENERATED by per-section-migrate. Edit freely — Bob will treat this
// file as the canonical source for the "about" section.

import React from 'react';
import AboutTextSplit from '@/components/sections/about/AboutTextSplit';
import SectionErrorBoundary from "@/components/ui/SectionErrorBoundary";

export default function AboutSection(): React.JSX.Element {
  return (
    <div id="about" data-section="about">
        <SectionErrorBoundary name="about">
              <AboutTextSplit
          title="Why Choose Amerigrass?"
          descriptions={[
            "We take the stress out of lawn care. Our subscription model ensures your lawn is always in top condition without you lifting a finger.",
            "Our team of professionals uses the best tools and techniques to guarantee reliable, consistent results for residential and commercial clients.",
            "No contracts and transparent pricing means you only pay for what you need. It is professional maintenance designed to fit your busy schedule.",
          ]}
          textAnimation="fade-blur"
        />
        </SectionErrorBoundary>
      </div>
  );
}
