// AUTO-GENERATED by per-section-migrate. Edit freely — Bob will treat this
// file as the canonical source for the "contact" section.

import React from 'react';
import ContactCta from '@/components/sections/contact/ContactCta';
import SectionErrorBoundary from "@/components/ui/SectionErrorBoundary";

export default function ContactSection(): React.JSX.Element {
  return (
    <div id="contact" data-section="contact">
        <SectionErrorBoundary name="contact">
              <ContactCta
          tag="Start Your Service"
          text="Call us at 321-371-1673 or email amerigrasscfl@gmail.com for a free quote or sign up today online."
          primaryButton={{
            text: "Call Now",
            href: "tel:3213711673",
          }}
          secondaryButton={{
            text: "Email Us",
            href: "mailto:amerigrasscfl@gmail.com",
          }}
          textAnimation="fade-blur"
        />
        </SectionErrorBoundary>
      </div>
  );
}
