/* eslint-disable */
// @ts-nocheck — generated by catalog-eject; runtime-correct but TS strict-mode false-positives on inlined catalog body
import ScrollReveal from "@/components/ui/ScrollReveal";
import TextAnimation from "@/components/ui/TextAnimation";
import Button from "@/components/ui/Button";

const primaryButton = {
  text: "Call Now",
  href: "tel:3213711673"
};
const secondaryButton = {
  text: "Email Us",
  href: "mailto:amerigrasscfl@gmail.com"
};

const ContactInline = () => {
  return (
    <section aria-label="Contact section" className="py-12 md:py-20">
      <div className="w-content-width mx-auto">
        <ScrollReveal variant="slide-up">
          <div className="flex flex-col items-center gap-6 md:gap-8 py-12 md:py-16 px-6 md:px-8 rounded card">
            <div className="flex flex-col items-center gap-4">
              <div className="px-3 py-1 text-sm card rounded w-fit">
                <p>{"Start Your Service"}</p>
              </div>

              <div className="flex flex-col items-center gap-4 max-w-3xl text-center">
                <TextAnimation
                  text={"Get a Free Quote Today"}
                  variant={"fade-blur"}
                  gradientText={true}
                  tag="h2"
                  className="text-3xl md:text-4xl lg:text-5xl leading-[1.15] font-semibold text-balance"
                />
                <p className="text-base md:text-lg text-accent text-balance">
                  Call us at 321-371-1673 or email amerigrasscfl@gmail.com for a free quote or sign up today online.
                </p>
              </div>

              <div className="flex flex-wrap justify-center gap-4 mt-2">
                <Button text={primaryButton.text} href={primaryButton.href} variant="primary" />
                <Button text={secondaryButton.text} href={secondaryButton.href} variant="secondary" animationDelay={0.1} />
              </div>
            </div>
          </div>
        </ScrollReveal>
      </div>
    </section>
  );
};

export default function ContactSection() {
  return (
    <div data-webild-section="contact" data-section="contact" id="contact">
      <ContactInline />
    </div>
  );
}
