// AUTO-GENERATED by per-section-migrate. Edit freely — Bob will treat this
// file as the canonical source for the "faq" section.

import React from 'react';
import FaqSimple from '@/components/sections/faq/FaqSimple';
import SectionErrorBoundary from "@/components/ui/SectionErrorBoundary";

export default function FaqSection(): React.JSX.Element {
  return (
    <div id="faq" data-section="faq">
        <SectionErrorBoundary name="faq">
              <FaqSimple
          tag="Common Questions"
          title="Need Help?"
          description="Answers to common questions about our subscription service."
          items={[
            {
              question: "Are there any hidden costs?",
              answer: "No. Our pricing is transparent and clearly outlined in our subscription tiers.",
            },
            {
              question: "Can I cancel anytime?",
              answer: "Yes, we offer a no-contract policy. You are free to cancel at any time.",
            },
            {
              question: "How do I schedule my service?",
              answer: "We provide a simple digital dashboard to manage all your scheduling needs.",
            },
          ]}
          textAnimation="slide-up"
        />
        </SectionErrorBoundary>
      </div>
  );
}
