// AUTO-GENERATED by per-section-migrate. Edit freely — Bob will treat this
// file as the canonical source for the "features" section.

import React from 'react';
import FeaturesMediaCards from '@/components/sections/features/FeaturesMediaCards';
import SectionErrorBoundary from "@/components/ui/SectionErrorBoundary";

export default function FeaturesSection(): React.JSX.Element {
  return (
    <div id="features" data-section="features">
        <SectionErrorBoundary name="features">
              <FeaturesMediaCards
          tag="Our Services"
          title="Everything Your Lawn Needs"
          description="Comprehensive monthly maintenance plans designed for a perfect lawn year-round."
          items={[
            {
              title: "Unlimited Mowing",
              description: "Professional weekly or bi-weekly mowing service.",
              imageSrc: "http://img.b2bpic.net/free-photo/flat-lay-gardening-composition_23-2148128654.jpg",
            },
            {
              title: "Weed Control",
              description: "Strategic treatments to keep your lawn pristine.",
              imageSrc: "http://img.b2bpic.net/free-photo/gardening-beautiful-spring-flowers-with-garden-supplies_169016-1828.jpg",
            },
            {
              title: "Easy Scheduling",
              description: "Manage your service dates through our simple dashboard.",
              imageSrc: "http://img.b2bpic.net/free-photo/handsome-male-using-tablet-outdoors_23-2148640385.jpg",
            },
          ]}
          textAnimation="slide-up"
        />
        </SectionErrorBoundary>
      </div>
  );
}
