// AUTO-GENERATED by per-section-migrate. Edit freely — Bob will treat this
// file as the canonical source for the "hero" section.

import React from 'react';
import HeroSplitMediaGrid from '@/components/sections/hero/HeroSplitMediaGrid';
import SectionErrorBoundary from "@/components/ui/SectionErrorBoundary";

export default function HeroSection(): React.JSX.Element {
  return (
    <div id="hero" data-section="hero">
        <SectionErrorBoundary name="hero">
              <HeroSplitMediaGrid
        tag="Premium Lawn Care Subscription"
        title="WHY CHOOSE AMERIGRASS?"
        description="Unlimited Mowing | Professional Edging | Weed Control | Reliable Scheduling. Starting Rates from just $45/month for standard lawns. Regular Rate: $60/month."
        primaryButton={{"href":"#contact","text":"Sign Up Today"}}
        secondaryButton={{"text":"Call 321-371-1673","href":"tel:321-371-1673"}}
        items={[{"imageSrc":"https://storage.googleapis.com/webild/users/user_3GMdm7yk6wEN7W9hhWl6vUrowgd/uploaded-1783793401529-96xzuw2l.png"},{"imageSrc":"https://storage.googleapis.com/webild/users/user_3GMdm7yk6wEN7W9hhWl6vUrowgd/uploaded-1783785580227-3m2sd2nr.jpg?_wi=1"}]}
        textAnimation="slide-up"
      />
        </SectionErrorBoundary>
      </div>
  );
}
