/* eslint-disable */
// @ts-nocheck — generated by catalog-eject; runtime-correct but TS strict-mode false-positives on inlined catalog body
import Button from "@/components/ui/Button";
import TextAnimation from "@/components/ui/TextAnimation";
import ImageOrVideo from "@/components/ui/ImageOrVideo";
import ScrollReveal from "@/components/ui/ScrollReveal";
import { cls } from "@/lib/utils";

const items = [
  {
    title: "Healthy Growth",
    description: "Lush vibrant green grass.",
    imageSrc: "http://img.b2bpic.net/free-photo/sunlight-sunny-land-scenic-weather_1127-2333.jpg"
  },
  {
    title: "Expert Team",
    description: "Professional care guaranteed.",
    imageSrc: "http://img.b2bpic.net/free-photo/professional-gardener-trimming-hedge-yard_342744-537.jpg"
  },
  {
    title: "Curb Appeal",
    description: "Better looking homes.",
    imageSrc: "http://img.b2bpic.net/free-photo/hotel-building-ho-chi-minh-vietnam_1262-3238.jpg"
  },
  {
    title: "Precision Edging",
    description: "Crisp borders every time.",
    imageSrc: "http://img.b2bpic.net/free-photo/close-up-gardener-cutting-pine-branches_23-2148396752.jpg"
  },
  {
    title: "Top Equipment",
    description: "Maintained and reliable.",
    imageSrc: "http://img.b2bpic.net/free-photo/arranged-boots-with-instruments-garden_23-2148028901.jpg"
  },
  {
    title: "Lawn Aeration",
    description: "Deep soil nourishment.",
    imageSrc: "http://img.b2bpic.net/free-photo/female-gardener-cutting-plants-with-pruner-greenhouse-woman-working-garden-cropped-shot-gardening-job-concept_74855-12777.jpg"
  },
  {
    title: "Garden Beauty",
    description: "Flowers and foliage care.",
    imageSrc: "http://img.b2bpic.net/free-photo/vertical-shot-beautiful-colorful-flowers-field_181624-7045.jpg"
  }
];

type FeatureItem = {
  title: string;
  description: string;
  href?: string;
} & ({ imageSrc: string; videoSrc?: never } | { videoSrc: string; imageSrc?: never });

interface FeaturesImageBentoProps {
  tag: string;
  title: string;
  description: string;
  primaryButton?: { text: string; href: string };
  secondaryButton?: { text: string; href: string };
  items: [FeatureItem, FeatureItem, FeatureItem, FeatureItem, FeatureItem, FeatureItem, FeatureItem];
  textAnimation: "slide-up" | "fade-blur" | "fade";
}

const ServicesBentoInline = () => {
  const gridClasses = [
    "md:col-span-2",
    "md:col-span-4",
    "md:col-span-3",
    "md:col-span-3",
    "md:col-span-2",
    "md:col-span-2",
    "md:col-span-2",
  ];

  const staggerDelays = [
    0,
    0.1,
    0,
    0.1,
    0,
    0.1,
    0.2,
  ];

  return (
    <section aria-label="Features image bento section" className="py-20">
      <div className="flex flex-col gap-8 md:gap-10">
        <div className="flex flex-col items-center w-content-width mx-auto gap-2">
          <div className="px-3 py-1 mb-1 text-sm card rounded w-fit">
            <p>{"Our Work"}</p>
          </div>

          <TextAnimation
            text={"Precision and Care"}
            variant={"fade-blur"}
            gradientText={true}
            tag="h2"
            className="md:max-w-8/10 text-6xl 2xl:text-7xl leading-[1.15] font-semibold text-center text-balance"
          />

          <TextAnimation
            text={"See the results of our professional lawn maintenance services in action. We service all of Central Florida and Tampa."}
            variant={"fade-blur"}
            gradientText={false}
            tag="p"
            className="md:max-w-7/10 text-lg md:text-xl leading-snug text-center text-balance"
          />

          {(undefined || undefined) && (
            <div className="flex flex-wrap justify-center gap-3 mt-2 md:mt-3">
              {undefined && <Button text={undefined.text} href={undefined.href} variant="primary"/>}
              {undefined && <Button text={undefined.text} href={undefined.href} variant="secondary" animationDelay={0.1} />}
            </div>
          )}
        </div>

        <div className="w-content-width mx-auto flex flex-col items-center gap-8 mb-4 md:mb-8">
          <img 
            src="https://storage.googleapis.com/webild/users/user_3GMdm7yk6wEN7W9hhWl6vUrowgd/uploaded-1783873541218-gtbbtaeo.jpg" 
            alt="Junk-It Logo" 
            className="w-full max-w-3xl rounded-lg shadow-md" 
          />
          <img 
            src="https://storage.googleapis.com/webild/users/user_3GMdm7yk6wEN7W9hhWl6vUrowgd/uploaded-1783873541219-vi26xijc.png" 
            alt="Junk-It Flyer" 
            className="w-full max-w-3xl rounded-lg shadow-md" 
          />
          <img 
            src="https://storage.googleapis.com/webild/users/user_3GMdm7yk6wEN7W9hhWl6vUrowgd/uploaded-1783873288884-pi06ag5p.png" 
            alt="Amerigrass Summer Special" 
            className="w-full max-w-3xl rounded-lg shadow-md" 
          />
        </div>

        <div className="w-content-width mx-auto grid grid-cols-1 md:grid-cols-6 gap-3">
          {items.map((item, index) => {
            const content = (
              <div className="relative h-80 xl:h-100 2xl:h-120 overflow-hidden">
                <ImageOrVideo
                  imageSrc={item.imageSrc}
                  videoSrc={item.videoSrc}
                  className="rounded group-hover:scale-105 transition-transform duration-500"
                />

                <div className="absolute inset-x-5 bottom-5 xl:inset-x-6 xl:bottom-6 2xl:inset-x-7 2xl:bottom-7 flex flex-col text-background">
                  <span className="text-2xl font-semibold leading-snug truncate">{item.title}</span>
                  <span className="text-base leading-snug truncate">{item.description}</span>
                </div>
              </div>
            );

            return (
              <ScrollReveal key={index} variant="fade" delay={staggerDelays[index]} className={cls("col-span-1 group", gridClasses[index])}>
                {item.href ? (
                  <a href={item.href} className="block overflow-hidden rounded">
                    {content}
                  </a>
                ) : (
                  <div className="overflow-hidden rounded">
                    {content}
                  </div>
                )}
              </ScrollReveal>
            );
          })}
        </div>
      </div>
    </section>
  );
};

export default function ServicesBentoSection() {
  return (
    <div data-webild-section="services-bento" data-section="services-bento" id="services-bento">
      <ServicesBentoInline />
    </div>
  );
}
