// AUTO-GENERATED by per-section-migrate. Edit freely — Bob will treat this
// file as the canonical source for the "services-bento" section.

import React from 'react';
import FeaturesImageBento from '@/components/sections/features/FeaturesImageBento';
import SectionErrorBoundary from "@/components/ui/SectionErrorBoundary";

export default function ServicesBentoSection(): React.JSX.Element {
  return (
    <div id="services-bento" data-section="services-bento">
        <SectionErrorBoundary name="services-bento">
              <FeaturesImageBento
          tag="Our Work"
          title="Precision and Care"
          description="See the results of our professional lawn maintenance services in action. We service all of Central Florida and Tampa."
          items={[
            {
              title: "Healthy Growth",
              description: "Lush vibrant green grass.",
              imageSrc: "http://img.b2bpic.net/free-photo/sunlight-sunny-land-scenic-weather_1127-2333.jpg",
            },
            {
              title: "Expert Team",
              description: "Professional care guaranteed.",
              imageSrc: "http://img.b2bpic.net/free-photo/professional-gardener-trimming-hedge-yard_342744-537.jpg",
            },
            {
              title: "Curb Appeal",
              description: "Better looking homes.",
              imageSrc: "http://img.b2bpic.net/free-photo/hotel-building-ho-chi-minh-vietnam_1262-3238.jpg",
            },
            {
              title: "Precision Edging",
              description: "Crisp borders every time.",
              imageSrc: "http://img.b2bpic.net/free-photo/close-up-gardener-cutting-pine-branches_23-2148396752.jpg",
            },
            {
              title: "Top Equipment",
              description: "Maintained and reliable.",
              imageSrc: "http://img.b2bpic.net/free-photo/arranged-boots-with-instruments-garden_23-2148028901.jpg",
            },
            {
              title: "Lawn Aeration",
              description: "Deep soil nourishment.",
              imageSrc: "http://img.b2bpic.net/free-photo/female-gardener-cutting-plants-with-pruner-greenhouse-woman-working-garden-cropped-shot-gardening-job-concept_74855-12777.jpg",
            },
            {
              title: "Garden Beauty",
              description: "Flowers and foliage care.",
              imageSrc: "http://img.b2bpic.net/free-photo/vertical-shot-beautiful-colorful-flowers-field_181624-7045.jpg",
            },
          ]}
          textAnimation="fade-blur"
        />
        </SectionErrorBoundary>
      </div>
  );
}
