// AUTO-GENERATED by per-section-migrate. Edit freely — Bob will treat this
// file as the canonical source for the "testimonials" section.

import React from 'react';
import TestimonialQuoteCards from '@/components/sections/testimonial/TestimonialQuoteCards';
import SectionErrorBoundary from "@/components/ui/SectionErrorBoundary";

export default function TestimonialsSection(): React.JSX.Element {
  return (
    <div id="testimonials" data-section="testimonials">
        <SectionErrorBoundary name="testimonials">
              <TestimonialQuoteCards
          tag="Happy Homeowners"
          title="What Our Clients Say"
          description="Join our community of satisfied homeowners."
          testimonials={[
            {
              name: "Sarah J.",
              role: "Homeowner",
              quote: "Amerigrass saved me hours every week. My lawn looks incredible!",
              imageSrc: "http://img.b2bpic.net/free-photo/woman-finding-out-she-s-expecting-going-be-mother_23-2150167530.jpg",
            },
            {
              name: "Mike D.",
              role: "Homeowner",
              quote: "Reliable and professional. Worth every penny for the subscription.",
              imageSrc: "http://img.b2bpic.net/free-photo/man-clapping-hands-isolated-studio_1303-30130.jpg",
            },
            {
              name: "Elena R.",
              role: "Homeowner",
              quote: "Great service, transparent pricing. Very happy with the team.",
              imageSrc: "http://img.b2bpic.net/free-photo/close-up-expressive-woman-with-blurred-background_1154-222.jpg",
            },
            {
              name: "David W.",
              role: "Homeowner",
              quote: "My lawn has never looked better. Amazing attention to detail.",
              imageSrc: "http://img.b2bpic.net/free-photo/medium-shot-man-correcting-grammar-mistakes_23-2150171372.jpg",
            },
            {
              name: "Linda P.",
              role: "Homeowner",
              quote: "Hassle-free lawn care is exactly what I needed for my busy schedule.",
              imageSrc: "http://img.b2bpic.net/free-photo/love-concept-with-happy-couple-spending-time-together_23-2149068853.jpg",
            },
          ]}
          textAnimation="fade"
        />
        </SectionErrorBoundary>
      </div>
  );
}
